[package]
name = "stop-nagging"
version = "0.1.0"
edition = "2021"
description = "A CLI tool to silence or disable upgrade/advertising nags from various JS ecosystem tools."
license = "MIT"
repository = "https://github.com/youruser/stop-nagging"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
clap = { version = "4.0", features = ["derive"] }
thiserror = "1.0"
