name: Installation Test

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  test-linux-install:
    name: Test Linux Installation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test installation script
        run: |
          curl -s https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/scripts/install_stop_nagging.sh | bash

      - name: Verify installation
        run: |
          stop-nagging --version
          # Test basic functionality
          stop-nagging check

  test-windows-install:
    name: Test Windows Installation
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test installation script
        shell: powershell
        run: |
          iwr https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/scripts/install_stop_nagging.ps1 -UseBasicParsing | iex

      - name: Verify installation
        shell: powershell
        run: |
          stop-nagging --version
          # Test basic functionality
          stop-nagging check
